### ISSUE TITLE
DateTimePicker Doesn't Work in IE11 Due To Flexbox Shorthand Syntax

### ISSUE THREAD

**Issue by kvnlnt** [telerik/kendo-themes#1042]
The DateTimePicker's use of the flex shorthand syntax is incompatible with ie11. flex shorthand declarations with unitless flex-basis values are ignored in ie11, (see: https://github.com/philipwalton/flexbugs#flexbug-4). The DateTimePicker is making using of the css function "calc" for flex-basis and therefore doesn't work in ie11. 

**Solution:**
Explicitly assign flex-grow, flex-shrink and flex-basis with the same values and it will work. 

![Annotation 2019-10-30 112702 PNG (1)](https://user-images.githubusercontent.com/577412/68041857-bd1f2000-fc8e-11e9-9804-3be4b3ad49f6.jpg)

**Comment by kvnlnt** [comment]
I've found another problem in IE11: After implementing my own fix in my css overwrite file (which does solve the problem I spelled out above) I've discovered that the animation between the date/time states is misbehaving. It intermittently doesn't always complete it's transition from the date to time, often clipping the left side of the time screen. Unfortunately I wasn't able to find a solution via css. If the animation is css driven it possibly needs to be moved into the component, if not then the component transition logic may need to be refactored.

**Comment by joneff** [comment]
I know it's been more than one year since the last activity of this item, but I was wondering, if you remember that is, do you get this behaviour out of the box, or when you build the theme from source?

Here is why I ask:
* I looked carefully for any unitless shorthand declarations and I found two, only in the upload component. The rest we have fixed
* I looked for calc for any flex basis in the **output**, and I've found none

We are using postcss-calc to mitigate a lot of IE related issues like nested calc expressions, but also to simplify our calc expressions to plain units, where possible. So if you are seeing those calc expressions as is, instead of simplified, that implies you are compiling from source.

We do have an article in this repository wiki -- https://github.com/telerik/kendo-themes/wiki/Compiling-themes -- which I know we should put in a more prominent location, so people can find it... Anyway, you could use the setup in the article to compile your themes and you should be able to get rid of the nasty calc in flex basis, if possible that is.
