### ISSUE TITLE
Border missing in vertically grouped agenda

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#1150]
**Describe the bug**
Missing border between resource and date columns

**To reproduce**
Open agenda with vertical grouping.

**Expected behavior**
There should be a border

**Screenshots**
![image](https://user-images.githubusercontent.com/8048/71974462-30f32100-321a-11ea-848e-bf2a1f289f17.png)

**Affected package**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please provide)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers**
- all

Related: #939 and #663

**Comment by silviyaboteva** [comment]
Not reproducible in React scheduler as the rendering is different (see demo here: https://www.telerik.com/kendo-react-ui/components/scheduler/views/agenda/#toc-grouping-by-resource).

**Comment by Dimitar-Goshev** [comment]
This issue is not fixed for Kendo UI for jQuery Scheduler - https://demos.telerik.com/kendo-ui/scheduler/resources-grouping-vertical?autoRun=true&theme=default-v2 - switch to Agenda view
![Vertical resources grouping in Kendo UI Scheduler - Google Chrome 2020-09-18 15 08 48](https://user-images.githubusercontent.com/6614183/93595714-ec32a300-f9c0-11ea-813f-f543e8962687.png)
