### ISSUE TITLE
Implement Responsive Pager

### ISSUE THREAD

**Issue by PreslavKozovski** [telerik/kendo-themes#121]
Implement Media Queries for Pager drop-downs, when the screen size is small, the pager buttons should become a drop-down. Similar to the LESS themes.

**Comment by PreslavKozovski** [comment]
KB on the topic:
https://docs.telerik.com/kendo-ui/knowledge-base/pager-responsive-numbers-sass-themes

**Comment by gyoshev** [comment]
I would like to suggest a different implementation of this feature for the SASS themes, namely using a class instead of relying on `@media` queries. The latter are very hard to customize with user code, and while they work for content that is guaranteed to take the complete width of the page, they are inadequate for components. Using a class to toggle this behavior allows the component to trigger the functionality only when it is necessary.

/cc @joneff

**Comment by joneff** [comment]
We'll take the approach described in the related duplicate issue: https://github.com/telerik/kendo-theme-default/issues/507#issuecomment-302709617

**Comment by nm-a** [comment]
Can you please share one example using angular grid.

**Comment by joneff** [comment]
Implementing responsive pager requires two things:

1) Place a select element with class .k-dropdown before pager numbers
2) Add `k-pager-sm|k-pager-md|k-pager-lg` class name depending on the resolution.

Examine related PR (#1322) to see exact markup in pager.html

Note: as we are extending the suite to have sizes, we are probably going to use those exact `-sm|-md-lg` suffixes and the markup could be changed. Still, [./tests/visual/pager.html](https://github.com/telerik/kendo-themes/blob/develop/tests/visual/pager.html), should show the latest version of how we implement the pager in the various suites.
