### ISSUE TITLE
Broken appearance when multiple sliders with labels are placed on top of each other

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-themes#140]
Example: https://dojo.telerik.com/@SiliconSoul/IYUloGaZ

**Comment by gyoshev** [comment]
This might require a few changes in the slider layout and rendering to allow it to expand when there are ticks. Here is [an example](https://dojo.telerik.com/iHENENEB) with preliminary version of the styles that could allow this.

**Comment by JoomFX** [comment]
This one seems to be fixed already.
[Here's how it looks](https://dojo.telerik.com/@ivalkov/IWIjobaj) with the current theme's version.

**Comment by joneff** [comment]
With less themes, yes. sass themes remain https://dojo.telerik.com/@joneff/Adotaviy

The issue is related to `.k-slider-horizontal .k-tick` having top margin. What happens is that it has a height of 100% and then additional top margin which in terms in height that's always more than 100% and float issues appear.
