### ISSUE TITLE
4.12.0 breaks node-sass argument `$color-2` of `mix($color-1, $color-2, $weight: 50%)` must be a color

### ISSUE THREAD

**Issue by Shereef** [telerik/kendo-themes#1557]
**Describe the regression**
I am updating our project from angular 7 to 9 but first I need to get to angular 8, trying to get there i got warnings which led me to beleive i need to update kendo, i ran `npx npm-check-updates -u -f /.*@progress.*/ --packageFile ./package.json` which gave me lots of stuff to update

at first I updated everything i got an error while running node-sass
I finally tracked it down to:
 @progress/kendo-theme-default              ^2.54.0  →      ^4.18.1

the specific version that breaks things is 4.12.0

**To reproduce**
I don't have a public repo that has the issue to show you.
but all i need to do is
* npm i @progress/kendo-theme-default@4.12.0 
* node-sass src/assets/themes/ -o src/assets/
I get the following error:

Error: 
argument `$color-2` of `mix($color-1, $color-2, $weight: 50%)` must be a color
        on line 340 of node_modules/@progress/kendo-theme-default/scss/functions/_colors.scss, in function `mix`
        from line 340 of node_modules/@progress/kendo-theme-default/scss/functions/_colors.scss, in function `color-level`
        from line 344 of node_modules/@progress/kendo-theme-default/scss/functions/_colors.scss, in function `tint`
        from line 124 of node_modules/@progress/kendo-theme-default/scss/_variables.scss
        from line 2 of node_modules/@progress/kendo-theme-default/scss/all.scss
        from line 62 of src/assets/themes/black-theme.scss
>>     @return mix($base, $color, $level * $color-level-step);

**Expected behavior**

**Screenshots**

**Affected package (please remove the unneeded items)**
* theme-default

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* Not Applicable

**Build system information (please remove the unneeded items)**
* OS: Windows
* Node version: v10.20.1
* NPM version: 6.14.5

**Additional context**
If i do 
* npm i @progress/kendo-theme-default@4.11
it works fine

**Comment by joneff** [comment]
Can you share `black-theme,scss` as a gist? Just from looking at the log, it's not possible to say which variable is causing the issue.

**Comment by Shereef** [comment]
> Can you share `black-theme,scss` as a gist? Just from looking at the log, it's not possible to say which variable is causing the issue.

I will share it tomorrow but it's crashing at the import line for all.scss then _varaiables.scss then you can see the rest from the stack trace

I'm currently away from my computer.

**Comment by Shereef** [comment]
> Can you share `black-theme,scss` as a gist? Just from looking at the log, it's not possible to say which variable is causing the issue.

https://gist.github.com/Shereef/a20e002f23cd07d3976eb81fbeca352c

**Comment by Shereef** [comment]
@joneff  any update on this ?

**Comment by Shereef** [comment]
We were using $primary in one of our scss files which caused the issue since kendo introduced the same exact variable

**Comment by joneff** [comment]
While we are yet to have update on that, we'll look into it. We got little overwhelmed by our roadmap.

Seems that there is connection between how primary is retrieved from Material... To be honest, we haven't tried that integration, yet.

Reopening.

**Comment by joneff** [comment]
This particular issue, and I am supposing some other, is related to "ownership" of variables and more specifically what a given variable means in the context of a project.

In the context of `@angular/material`, `$primary` variable refers to the primary palette, where as in kendo-themes, it refers to the primary color. And I mean color, not custom property (css variable).

How can the issue be resolved? Sort of...

**Rename user variables**

For material themeing, prior the migration to sass modules, did not really care how a given variable is called, as long as a certain mixin got its input, that's one way to workaround it: use variables like `$primary-palette` and `$accent-palette`. Of course that may or may not suit a given project.

**Rename Kendo variables**

That's actually the only true way to solve the issue -- if we use scoped i.e. `$kendo-` variable we more or less ensure that we "own" those variables and we can define which variable accepts what type of value.

That, however, is a huge undertaking.

**Use sass modules**

Also an option, but equally hard, if not harder, to renaming kendo variables. That also breaks compatibility with `node-sass` completely, because the latter does not understand a thing about sass modules.

---

**What's next?**

For the time being -- nothing. We can't resolve the issue in either way... yet! I am assuming, as sass modules get up to speed and the old syntax gets dropped from dart-sass, we'll have one final stable version for node-sass and then migrate to dart-sass.

Sadly, I am closing the issue, due to lack of resolution.
