### ISSUE TITLE
Customize the Tooltip callout element

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-themes#1628]
**Describe the bug**
The current styles do not allow customizing the _callout_ element of the Kendo Angular Tooltip component:
![Capture](https://user-images.githubusercontent.com/33104481/84761657-69b9d200-afd2-11ea-9b01-6337018ea088.PNG)

https://www.telerik.com/kendo-angular-ui/components/tooltip/default-conf/

**Comment by JoomFX** [comment]
The callout (arrow) element is supposed to have the same background-color as the main tooltip element.
This background-color can be customized by setting the `$tooltip-bg` variable to the value you want.

The callout element cannot have a border because it is actually a border itself (it is visualized by using the `border` CSS property - `border-width: 6px;`).
Using the `border` property is a common way for creating such callout/arrow elements as you can see in [Bootstrap 4 Tooltip](https://getbootstrap.com/docs/4.5/components/tooltips/) as well.
