### ISSUE TITLE
DropDownList is misaligned when nested in a flex container

### ISSUE THREAD

**Issue by IvanDanchev** [telerik/kendo-themes#1786]
**Describe the bug**
The DropDownList when nested in a inline-flex container appears misaligned, compared to other editors (ComboBox, textbox, etc.). The misalignment is more noticeable when there is no data in the DropDownList. In the example linked below, if you uncomment the data in the DataSource, the DropDownList will be displayed 1px below the other editors. 

**To reproduce**

1. Go to [https://dojo.telerik.com/UKoJOSiH](https://dojo.telerik.com/UKoJOSiH)

**Expected behavior**
The DropDownList is aligned with the other editors

**Screenshots**

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**
N/A

**Comment by joneff** [comment]
As far as I can see it is related to two things:

* dropdownlist (and dropdown tree for that matter) uses span instead of input. while we do everything to have them behave the same, there appears to be a difference
* inline-flex containers appear to have trouble with `vertical-align: baseline`, unlike inline-block containers. Any other alignment works well.

I've created a sample dojo: https://dojo.telerik.com/@joneff/aLOJijaV.

Since the issue can easily be overcome by tweaking styles, I am lowering the severity.

**Comment by TeyaVes** [comment]
no longer reproducible as of kendo v. 2022.1.119 :  https://dojo.telerik.com/aSAQudId
