### ISSUE TITLE
SassError: Incompatible units em and px.

### ISSUE THREAD

**Issue by thhet** [telerik/kendo-themes#1980]
**Describe the bug**
Error "SassError: Incompatible units em and px." when trying to build 

**To reproduce**
Build (ng build) or start (ng serve).

**Expected behavior**

**Screenshots**
![SassError](https://user-images.githubusercontent.com/25905746/96086768-15acf480-0ec3-11eb-93fc-f6d188f3a095.png)

**Affected package (please remove the unneeded items)**
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Build system information (please remove the unneeded items)**
* OS: Windows
* Node version: 10.13.0
* NPM version: 6.9.0

**Additional context**
angular 10.1.6
kendo-theme-material": "^3.20.0"

**Comment by tomvanoost** [comment]
I have this issue for a while, stuck on the 3.20.0 version of the theme. Is this going to be solved anytime soon?

**Comment by joneff** [comment]
@tomvanoost  @thhet 

The problem is solved in the sass files for a while now. That string interpolation you are seeing on line 3442 in the screenshot or https://github.com/telerik/kendo-themes/blob/fbea5f406a2b2d038927676da546dc4cd578bfd2/packages/default/scss/common/_loading.scss#L103 in the code, is precisely to target that behaviour in sass compilers.

We have a total of 3 such usages and all them are interpolated.

I have also commented in the commit -- 7b558a6071ac76aa764034548781228a53ea890b -- that this is the fix, not the issue.

The only case in which you could see this error if you are trying to load the compiled css file trough the sass compiler again, in which case, yes, it will fail.

If that is the case, use `all.scss` and not `all.css`, or exclude the css files from being loaded trough webpack sass-loader.

**Comment by joneff** [comment]
A quick note: if your webpack config looks anything like that:

```json
module.exports = {
  module: {
    rules: [
      {
        test: /\.s?css$/i, // emphasis on the test rule!
        use: [
          "style-loader",
          "css-loader",
          "sass-loader"
        ],
      },
    ],
  },
};
```

you are bound to have the error. The rule defines that **css files should be treated like sass files**. True, in most cases it wouldn't matter and yet, this is among the few cases that does matter.

The solution is to not treat css files like sass files and instead use two separate rules -- one for sass and one for css.

**Comment by tomvanoost** [comment]
Thank you @joneff very helpful.
