### ISSUE TITLE
Revise filter multi checkbox menu styles

### ISSUE THREAD

**Issue by Stamo-Gochev** [telerik/kendo-themes#2119]
The rendering of the filter multi checkbox menu can be revised as discussed with @joneff and @PreslavKozovski.

The component will be supported as both a standalone menu (similar to the current filter menu) and also as part of the column menu (refer to https://github.com/telerik/kendo-ux-private/issues/147)

Here is the current rendering in react:
https://www.telerik.com/kendo-react-ui/components/grid/filtering/#toc-column-menu-filter

ng2 demonstrates this menu as a custom component in a template:
https://www.telerik.com/kendo-angular-ui/components/grid/filtering/reusable-filter/#toc-multi-checkbox-menu-filtering

Currently, there is a misalignment of the search icon in bootstrap and material themes in https://www.telerik.com/kendo-react-ui/components/grid/filtering/#toc-column-menu-filter:

- bootstrap
![image](https://user-images.githubusercontent.com/1857705/101336602-57369c00-3883-11eb-907e-e59996466a91.png)

- material
![image](https://user-images.githubusercontent.com/1857705/101336545-49811680-3883-11eb-80ce-ba25931d2f5c.png)

Additional things that should be considered that are missing in the current version of React:
- [ ] add a clear icon in the searchbox that appears when the user enters a value (similar to a ComboBox) that allows clearing the entered text (not the filter)
- [ ] when the text in the searchbox is such that no results are found, a "no data template" should be displayed ( with `.k-no-data`)

Additional issues:
- https://github.com/telerik/kendo-themes/issues/2187

**Comment by Stamo-Gochev** [comment]
https://github.com/telerik/kendo-themes/issues/2187

**Comment by PreslavKozovski** [comment]
To fix this issue, we should apply the new rendering for the Searchbox in all Kendo flavors.

```
<span class="k-searchbox">
    <input class="k-input" type="text" value="Normal">
    <span class="k-input-suffix">
        <button type="button" class="k-button k-button-clear k-icon-button"><span class="k-icon k-i-close"></span></button>
        <span class="k-icon k-i-search"></span>
    </span>
</span>
```

cc: @telerik/kendo-front-end

**Comment by PreslavKozovski** [comment]
@VicTachev @jivanova @Xizario To resolve this problem and achieve the new design, I had to change the filter menu checkbox popup rendering. So, to apply the new styles, we will need to change the HTML in the flavors as I demonstrated here - https://github.com/telerik/kendo-themes/blob/develop/tests/visual/grid-filter-menu-multi-checkbox.html

@inikolova I am not pining a person from the Angular team because I see that our Angular grid does not provide an out-of-the-box Multi Check Filter Popup but only a custom template (demo), please, correct me if I am wrong.

Further, @VicTachev, the new design makes the Boolean Filter Menu a case of the Multi-Check menu, so we might need to revise the template in jQuery.
