### ISSUE TITLE
feat: TreeView filtering

### ISSUE THREAD

**Issue by tapopov** [telerik/kendo-themes#2121]
We're missing the input styles:

![image](https://user-images.githubusercontent.com/5184468/101463125-b0670400-3945-11eb-85dd-4b3b6f49d9e6.png)

**Comment by gkarapeev** [comment]
Thought it might be worth mentioning that [in my WIP](https://github.com/telerik/kendo-angular-treeview/pull/148) I'm using a kendo-textbox, but it seems like an overkill to me if a few styles could do the same without dragging along another dependency.

Just wanted to avoid confusing somebody that using a kendo-textbox is a set decision. It's just my wip.

**Comment by gkarapeev** [comment]
After some discussion with @JoomFX @dimitar-pechev and @tsvetomir, decided to use a kendo-textbox instead of adding custom HTML to the TreeView + styles for it in the themes.

The reason is that besides the search icon, the kendo-textbox also has the "clearButton" functionality built-in, and that justifies adding the extra peer dependency to the TreeView package.

No further action is required here.
