### ISSUE TITLE
ScrollView contents overflowing container

### ISSUE THREAD

**Issue by andrewlutgen** [telerik/kendo-themes#2159]
**Describe the bug**
ScrollView content overflows bounds of container. May be an issue related to latest version (4.29)

**To reproduce**
This can be seen in Telerik's own example page for the Angular UI control (Chrome version noted below). Or view screenshots below.

1. Go to https://www.telerik.com/kendo-angular-ui/components/scrollview/#toc-basic-usage
1. Observe overflow. All ScrollView items can be seen overflowing container.

**Expected behavior**
ScrollView content is contained within container.

**Screenshots**
![image](https://user-images.githubusercontent.com/18523358/102387250-c30cb900-3f95-11eb-993f-fa1ff7718254.png)

![image](https://user-images.githubusercontent.com/18523358/102389299-83939c00-3f98-11eb-9dd0-cbc78d52edc0.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites**
* Kendo UI for Angular

**Affected browsers**
* Firefox
* Edge
* Safari
* Chrome version: Version 87.0.4280.88 (Official Build) (64-bit)

**Build system information**
* Not Applicable

**Additional context**
Issue may be related to theme-default version 4.29. Reverting to 4.28.0 appears to fix the issue.

**Comment by inikolova** [comment]
This outcome is due to some breaking changes in the rendering of the Kendo UI for Angular ScrollView Component, more precisely:

- k-scrollview and k-scrollview-wrap CSS classes are displaced;
- Scrollview Pager now has the k-scrollview-nav-wrap CSS class.

Please upgrade the component to v4.0.0 - this should address the problem

https://www.telerik.com/kendo-angular-ui-develop/components/scrollview/
