### ISSUE TITLE
DateTimePicker popup doesn't fit its content

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#2443]
**Describe the bug**
Using [weekNumber]="true" causes the Popup to cut off its content.

**To reproduce**
Please see the following example:

https://stackblitz.com/edit/angular-2ymdyp-brg3mn?file=app%2Fapp.component.ts

**Expected behavior**
The popup content shouldn't be cut off.

**Comment by yanmariomenev** [comment]
In the meantime until the issue is resolved, as a workaround, the font-size of the popup can be increased by a little bit:
` encapsulation: ViewEncapsulation.None,
  styles: [
    `
      **.k-popup {
        font-size: 15px;
      }**
    ``
StackBlitz example: https://stackblitz.com/edit/datetimepicker-popup-font-size-week-number-display-bug?file=app/app.component.ts
