### ISSUE TITLE
Rendering for layout components

### ISSUE THREAD

**Issue by jivanova** [telerik/kendo-themes#2454]
## Meta

<details>

* Aha item -- (https://progresssoftware.aha.io/features/BLZR-206
* Design issue -- N/A https://github.com/telerik/kendo-ux-private/issues/347
* Dev team issue - https://github.com/telerik/blazor/issues/2357 & https://github.com/telerik/blazor/issues/2565

</details>

We will release StackLayout and GridLayout components.

### StackLayout

**API**
https://github.com/telerik/blazor/issues/2357#issuecomment-851047099

**Dev spike**
https://github.com/telerik/blazor/tree/layout-components

**Rendering requirements**
- Base classes for stacklayout
- Support for horizontal and vertical orientation
- Support for horizontal (alignment to x axis) of the items
        - Center, Right, Left, Stretch values
- Support for vertical(alignment to y axis) of the items
        - Center, Top, Bottom, Stretch values

<details>
<summary> ⬇️  Details on the alignment options</summary>

Flex styling through `justify-content` and `align-items` differ based on the orientation as they are applicable to main and cross axis. However, the component will handle the swap of the styling to provide intuitive horizontal and vertical alignment.

Playground with stacklayout:

![stacklayout](https://user-images.githubusercontent.com/7159157/120446608-61e57000-c392-11eb-9b31-51ba74751413.gif)

</details>

- Example rendering of nested stacklayouts with stretched layouts
- Research if scrollable feature could be added as rendering of StackLayout ( might be considered for v2)

### GridLayout

**API**
https://github.com/telerik/blazor/issues/2565#issuecomment-851152567

**Dev spike**
https://github.com/telerik/blazor/tree/layout-components

- Base classes for gridlayout
- Support for horizontal (alignment to x axis) of the items
        - Center, Right, Left, Stretch values
- Support for vertical(alignment to y axis) of the items
        - Center, Top, Bottom, Stretch values

The distribution of rows/columns and spacing will be handled through inline styles.

**Blazor release: 23.06. Themes release: 14.06**

**Comment by joneff** [comment]
Perhaps the best description I've seen is

![image](https://user-images.githubusercontent.com/8048/117106914-5e59cb80-ad89-11eb-915b-98f20031913d.png)

The important bit is that those layout are components with single level nesting -- **they only control their immediate descendants (children)**.

### Flexbox based layout

The behaviour of components should adhere to the following:

* generic flex layout -- can change direction, set spacing, wrapping, align etc...
* generic stack layout -- can change direction, set spacing, align etc. **can not set wrapping**
* horizontal layout (hstack or hbox) -- horizontal direction. can set spacing, align etc. **can not set direction and wrapping**
* vertical layout (vstack or vbox) -- vertical direction. can set spacing, align etc **can not set direction and wrapping**

We may need a generic flex layout child component to set self behaviour. We could have it be "transparent" e.g. props are applied on actual child or opaque e.g. we props are applied on additional wrapper.

### Grid based layout

The name is pretty self explanatory -- it's a css grid based layout. As with the flex layout we may need a generic grid layout child component to specify various self props.

### Absolute layout

This one actually needs own child component, otherwise we wont' be able to position anything.
