### ISSUE TITLE
Textarea with form-control has wrong appearance

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/kendo-themes#2460]
**Describe the bug**
All inputs need to integrate with the bootstrap `form-control` class because it is ubiquitous. The textarea has the following issues (at least with autosize is set to true)

* width is not 100%
* content overflows the border - the border is on the top span not the textarea
* height is wrong - it is set on the wrapping element but the textarea node iteself gets taller with autosize
* there is a box shadow on the wrong spot (the span not the textarea), if there hasto be a shadow at all

reported in 1518433, **public in 1518471**

**To reproduce**

```razor
@* make sure you have bootstrap css referenced in the project *@

<TelerikTextArea @bind-Value="@theValue" Class="form-control" AutoSize="true" />

@* You can compare with this *@
@* <textarea class="form-control" @bind="theValue"></textarea> *@

@code{
    string theValue { get; set; } = "one\ntwo\nthree\nfour";
}
```

**Expected behavior**

the expected pretty appearance, maybe something like this (note that this is with my css workarounds from the public item and there is a chance I missed something)
![something0like-expected-appearance](https://user-images.githubusercontent.com/5746515/117246963-26648e00-ae46-11eb-8a7c-2de0e9d0f443.png)

**Screenshots**
problem
![wrong-appearance](https://user-images.githubusercontent.com/5746515/117246872-06cd6580-ae46-11eb-9dcc-bc388f60583f.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**

* Telerik UI for Blazor

others might be affected as well, I have not tested and I am not sure they all have the autosize feature

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment]
Our components cannot and will not integrate with third party class names and here is why:

* class names are usually rendering specific. meaning, we should comply to certain rendering in order to have the styles applied
* since that's not the case, we need to handle each and every case we have for a given class name, by overriding styles in the following manner `.k-combobox.form-control`

It may seem like not a big deal, but it is: who's to say which classnames do we we adapt?

Instead, we'll be providing class names in our themes and functionality in our components to achieve the desired behaviour.

**Comment by marin-bratanov** [comment]
I recommend posting an update in the public portal with some reasoning.
