### ISSUE TITLE
No indication (material theme) of a required input (w/o label)

### ISSUE THREAD

**Issue by getsetbro** [telerik/kendo-themes#255]
## I'm submitting a...
* Bug report

## Current behavior
With the Material theme there is no indication that a input is required unless it includes a label.

## Expected behavior
There would be an indication that an input is required.

## Minimal reproduction of the problem with instructions
Shown here
https://stackblitz.com/edit/react-ca33uy-uf8g73

## What is the motivation or use case for changing the behavior?
Usability 

## Environment
React 16.4.2

Browser:
- Chrome (desktop) version XX

System:
MAC

**Comment by elena-gancheva** [comment]
The issue has been fixed and is available in the [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the themе.

**Comment by getsetbro** [comment]
Is this for React too or only Angular?

**Comment by elena-gancheva** [comment]
Hi @getsetbro, the fix is available in the [development builds](https://www.telerik.com/kendo-angular-ui/components/installation/development-builds/) of the themе. This means the issue is fixed for React as well. I have updated this [stackblitz ](https://stackblitz.com/edit/react-ca33uy-pgpexl)example for a reference.
