### ISSUE TITLE
Broken TabStrip styles in version 4.41.0

### ISSUE THREAD

**Issue by kosimas** [telerik/kendo-themes#2722]
## I'm submitting a...

* Bug report 

## Current behavior

Since version 4.41.0 the TabStrip component looks very diffrent, compared to version 4.40.1. I'm not sure if this is intentional or a mistake. There is nothing mentioned in the changelog so I assume it is a mistake.
## Expected behavior

If it is a mistake, the changes should be reversed or fixed.
## Minimal reproduction of the problem with instructions

With latest theme version
https://stackblitz.com/edit/react-t1l17k?file=app/main.tsx

Last working theme version
https://stackblitz.com/edit/react-bz5fzu?file=index.html

**Comment by silviyaboteva** [comment]
We made an enhancement in the TabStrip's styles and rendering in the latest version and you can see the issue here for more information: https://github.com/telerik/kendo-themes/issues/2628.

The rendering updates for the React component are already released in dev version. You can see them if you update the `@progress/kendo-react-layout` package to the latest dev: https://stackblitz.com/edit/react-t1l17k-5xjwi8?file=index.html.

And a new feature request was logged for implementing sortable and scrollable tabs for the TabStrip in our public issue tracker: https://github.com/telerik/kendo-react/issues/1044. You can add thumbs up if you like to see this implemented.
