### ISSUE TITLE
.k-list .k-item.k-state-focused Not Using `$list-item-focused-shadow`

### ISSUE THREAD

**Issue by DaleyKD** [telerik/kendo-themes#2888]
**Describe the bug**
In the bootstrap theme, you're hardcoding the box-shadow instead of using `$list-item-focused-shadow`.

**Expected behavior**
We should be able to use the `$list-item-focused-shadow` variable.

**Affected package (please remove the unneeded items)**
* theme-bootstrap

**Comment by silviyaboteva** [comment]
This will be fixed with the upcoming R1 2022 version, e.g. `v5`. We have exposed a separate list module where the renamed `$kendo-list-item-focus-shadow` variable is used by all themes.

Link for reference: https://github.com/telerik/kendo-themes/blob/v5-dev/packages/bootstrap/scss/list/_variables.scss#L224 and https://github.com/telerik/kendo-themes/blob/v5-dev/packages/bootstrap/scss/list/_theme.scss

**Comment by silviyaboteva** [comment]
Fixed with 15095429fba919f86a59e2f862b7b5415122f2b4.
