### ISSUE TITLE
New PivotGrid rendering shrinks items in FF

### ISSUE THREAD

**Issue by ag-petrov** [telerik/kendo-themes#2906]
When viewing the new Pivot in a pivot container with a configurator and button in FF the layout seems to be broken. Can be observed in [this ](https://www.telerik.com/kendo-react-ui/components/pivotgrid/)demo 

## Workaround
As a temporary workaround one can set to **k-flex** to the pivot and **k-flex-none** to the button and configurator.

**Comment by Juveniel** [comment]
The auto value that is used for the Pivot `grid-template-columns`  works with max-content which is [partially supported in Firefox](https://caniuse.com/?search=max-content), thus leading to the observed behavior difference in Chrome/Firefox. 

The issue can be resolved by using [the fr sizing algorithm ](https://www.w3.org/TR/css3-grid-layout/#algo-find-fr-size)instead of auto. 

```html
<div id="pivotgrid" style="height: 700px; grid-template-columns: 300px 1fr; grid-template-rows: 110px 1fr;">...</div>
```

/cc @silviyaboteva, @kspeyanski

**Comment by silviyaboteva** [comment]
Changing `auto` to `1fr` will break the widths of the table columns. Check this screenshot for reference:
<img width="1033" alt="Screenshot 2021-11-03 at 9 56 05" src="https://user-images.githubusercontent.com/17604855/140025725-7efcdca6-9ad2-440d-9d6b-a1adf5f9b436.png">
