### ISSUE TITLE
z-index of k-tabstrip-items-wrapper causes issues

### ISSUE THREAD

**Issue by JoomFX** [telerik/kendo-themes#2909]
**Describe the bug**
If there is a Dialog in the Tab content, the `k-tabstrip-items-wrapper` element stays above the overlay because it has a higher `z-index` than the `k-content` element.
For reference - ticket 1539612.

**To reproduce**

1. Go to [this Stackblitz example](https://stackblitz.com/edit/angular-o1ed16-y1vnk3?file=app/app.component.ts)
1. Click on the "Open dialog" button
1. Notice how the tabs are above the overlay

**Expected behavior**
Since we use the `z-index` on the `k-tabstrip-items-wrapper` element for styling purposes only (so the border of the `k-tabstrip-items` element can be visible) we can remove it and add a 1px margin instead.

**Screenshots**
![tabstrip](https://user-images.githubusercontent.com/7753940/138446290-acf0d2c1-fa05-4cc1-8f3c-6d5ed22fafee.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by pclancysc** [comment]
I disagree.  This is a breaking change since previously the tab container had no z-index and nested elements with z-index value would be treated as if they were at a root level (or whatever child element order had been set).  But now, because the tab content has a z-index value any nested items with a z-index value will be treated as relative from that element and hence all existing code where dialogs were nested inside tabs no longer work as they did.

**Comment by snisar** [comment]
Was this fixed, as I am still seeing an issue when opening a dialog within a tab on the latest release. Thanks

**Comment by pateldips** [comment]
I am having the issue with the same. I am using "@progress/kendo-angular-layout": "^6.5.0"

this is what they have

.k-tabstrip-items-wrapper{
    z-index: 2;
}

I have replaced with this, but top border disappearing because of it. 

.k-tabstrip-items-wrapper{
    z-index: inherit;
}

I got the same issue with Bootstrapper 5.0, they also using as below. 
.input-group .btn{
    z-index: 2;
}

**Comment by rajaharahap** [comment]
you can add this css :

.k-tabstrip-items-wrapper{
  z-index: 1;
  border-color: rgba(0, 0, 0, 0.08);
  color: #424242;
}
.k-tabstrip-top > .k-tabstrip-items-wrapper {
  border-bottom-width: 1px;
  margin-bottom: 0px;
}

if you use angular, you can add this css in global styles.css

**Comment by pateldips** [comment]
> 

thank you rajaharahap. that worked well.

**Comment by joneff** [comment]
FYI: #4085 resolves the z-index issue, by refactoring the structure of the tabstrip.

Still, having a window element inside any container, other than the `body` element, may result in unwanted (but expected) behaviour. One such unwanted behavour would be setting transition and overflow to the tabstrip content element like so:

```css
.k-tabstrip .k-content {
    transform: translateZ(0);
    overflow: hidden;
}
```
