### ISSUE TITLE
Tabs Overflowed When Scrollable False

### ISSUE THREAD

**Issue by PMcDonough11** [telerik/kendo-themes#2927]
**Describe the regression**
Using the latest version of Kendo UI, if the Kendo UI TabStrip is set to [scrollable: false](https://docs.telerik.com/kendo-ui/api/javascript/ui/tabstrip/configuration/scrollable), the tabs flex styling/structure is affecting the appearance of the tabs.  

**To reproduce**

1. Go to the [following Progress Kendo UI Dojo](https://dojo.telerik.com/@PMcDonou/odiBAHIC)

**Expected behavior**
Previously in Kendo UI version 2021.2.616, setting the scrollable to false will wrap the tabs above each other.  
[Working example](https://dojo.telerik.com/@PMcDonou/utUNateN)

**Screenshots**
![TabsAppearanceIssue](https://user-images.githubusercontent.com/19593058/139268574-a4520c7d-aff8-4379-a082-21f4134c597b.jpg)

**Affected suites**
* Kendo UI for jQuery

**Affected browsers**
* All

**Build system information**
* Not Applicable

**Comment by bzamfir** [comment]
I did a further test using latest version, 2021.3.1109, and the problem still persists

However I did some additional tests and I discovered the actual problem is in the kendo.common.min.css file

In the Dojo test  - https://dojo.telerik.com/UNUtEmij try the following:

- set the library to Kendo UI 2021 R3 SP1 (2021.3.1109)

- edit the line for kendo.common.min.css to use version 2021.2.616

`    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2021.2.616/styles/kendo.common.min.css">
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2021.3.1109/styles/kendo.rtl.min.css">
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2021.3.1109/styles/kendo.default.min.css">
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2021.3.1109/styles/kendo.mobile.all.min.css">
    
    <script src="https://code.jquery.com/jquery-1.12.3.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2021.3.1109/js/angular.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2021.3.1109/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2021.3.1109/js/kendo.all.min.js"></script>
` 

And the tabs are rendered correctly
So it appears the issue is in the specific CSS for the tabstrip, somewhere in the changes between 2.616 and the next version

**Comment by bzamfir** [comment]
Just checking ... this issue isn't fixed yet in 2022.1.412

https://dojo.telerik.com/UBacAkON/2

![image](https://user-images.githubusercontent.com/4658652/167688951-bcd77a52-b801-4608-8ac3-f7c58e644ff0.png)

Any update on the progress and the estimation for fix date?

**Comment by epetrow** [comment]
@bzamfir This has already been [fixed](https://dojo.telerik.com/ozARuGeh/2) in the SASS themes.

Since in your example you are using LESS themes, I have logged a separate [issue](https://github.com/telerik/kendo-ui-core/issues/6833) in the appropriate repo which you can track.
