### ISSUE TITLE
Implementation Discrepancies

### ISSUE THREAD

**Issue by imasyuko** [telerik/kendo-themes#2958]
1. **The Breadcrumb item with icon only** is not centered in all three themes.

<img width="494" alt="Screenshot 2021-11-11 at 11 32 34" src="https://user-images.githubusercontent.com/81818548/141274163-6589d856-8b4a-4ddb-88af-a9ec97d74013.png">

<img width="567" alt="Screenshot 2021-11-11 at 11 32 18" src="https://user-images.githubusercontent.com/81818548/141274171-0944816d-9501-46d9-8173-4be28c05600e.png">

<img width="530" alt="Screenshot 2021-11-11 at 11 32 51" src="https://user-images.githubusercontent.com/81818548/141274181-5e43319b-9f31-4ca7-bea6-be6e27e2277a.png">

2. **AppBar height** in all three themes.

- in Default - the height in implementation is 39px, but the usage of buttons suggests we need to extend it to 46px.

- in Bootstrap - the height in implementation is 42px, but the usage of buttons suggests we need to extend it to 54px.

- in Material - the height in implementation is 37px, but the usage of buttons suggests we need to extend it to 52px.

3. **ButtonGroup in focused state** in Bootstrap:
The buttons now have an outer shadow which differs from the ButtonGroup in Default.
![button-group-default](https://user-images.githubusercontent.com/81818548/141294365-cf522baf-b641-42b8-bd57-8c0be126cf75.png)                         ![button-group-bootstrap](https://user-images.githubusercontent.com/81818548/141294386-9e3a9adf-5f1e-4104-bc1e-98fc220c1910.png)

4. **Pager buttons in hover state** in Bootstrap
Their border color (D6D9DC) isn't used anywhere else.

5. **The header color in ListView** in Bootstrap (A0A0A0) isn't used anywhere else.

6. **The header of TileLayout** in all three themes:
We had to create new text styles as the header's properties in the implementation don't match with any other styles in our library.

**Comment by silviyaboteva** [comment]
After an offline sync with @epetrow, we saw the following:
- Points 1 (The Breadcrumb item with icon only) and 2 (AppBar height) are now fixed with v5 of the themes.
- Point 3 (ButtonGroup in the focused state): @imasyuko, @ivelina-penkova can you help here as I can see from the Figma Kits, in Default theme the button has an outer focus shadow, however, buttons in a button group have inner focus shadow. Is this expected behavior? In Bootstrap theme both cases (standalone button and in button group) have outer focus shadow. Is this expected? If the designs are correct, then in the implementation, we have to address the inner focus shadow for the Default theme only.
- Point 4 (Pager buttons in hover state): For the hover border of the pager numbers, we use the `$pager-number-hover-border` variable which inherits the global  `$hovered-border` [reference link](https://github.com/telerik/kendo-themes/blob/develop/packages/bootstrap/scss/_variables.scss#L284). It produces the exact #D6D9DC color as per design.
- Point 5 (The header color in ListView): I see that we use inline styles in the ListView demos setting font-size: 14px and color: #a0a0a0. These styles are not provided by the themes (themes actually do not provide any color customization for the headers and footers specifically). @imasyuko, do we need to update something here?
- Point 6 (The header of TileLayout): TileLayout uses the card classes for the tiles and applies the styles for the card title and card body. In the design (Default theme for example) I can see that the font size is bigger (16px) and the line height is some strange number (18.75px). @imasyuko, Can we unify the styles of the tile like card ones?

Thanks in advance! :)

**Comment by imasyuko** [comment]
**Point 1:** Great :)

**Point 3:** In the Figma UI kits, the buttons of ButtonGroup in focused state have been always using an inner shadow (v.1 - v 1.9). There was a moment when the visual tests matched the design file. In their current implementation, however, they use outer shadows (I don't know why). 

I changed the inner shadow of Bootstrap's ButtonGroup from inner to outer because with its current properties (after theme update) it would look this way:

<img width="733" alt="Screenshot 2022-02-08 at 15 13 46" src="https://user-images.githubusercontent.com/81818548/153003898-00c2ab31-2bed-4ce4-acb9-c923e0dff059.png">

The reason why in Default theme the shadow differs from the one in Bootstrap is because it would look this way:

<img width="557" alt="Screenshot 2022-02-08 at 14 39 46" src="https://user-images.githubusercontent.com/81818548/153003882-2d660377-aa84-4540-8eb4-a0347ff1c4c4.png">

In my opinion, all the buttons in focused state need to have an inner shadow because the outer shadow looks odd, and the buttons look like cropped. This needs further discussion may be in the FE-Design meeting.

**Point 5:** I asked particularly about this color as we didn’t use it anywhere else, but if you are okay with that, we could change it to $base-text instead (both in the design file and the demo).

**Point 6:** Sure, it’s done :)

**Comment by silviyaboteva** [comment]
Point 3: Sure, we can discuss it in the upcoming meeting :)
Point 5: yes, $base-text is ok as it currently the root listview element assigns this color: `.k-listview { color: #424242; }`. We can just remove the additional color from our demos :)

**Comment by Juveniel** [comment]
The Menu variables in bootstrap are already mapped to the $header-bg/text/border:

```scss
$menu-bg: $header-bg !default;
$menu-text: $header-text !default;
$menu-border: $header-border !default;
```

However, there we have another issue with the text receiving additional opacity overlay that makes the text color indistinguishable from the background.

**Comment by imasyuko** [comment]
The color of TileLayout's chrome area was changed in [the design file](https://www.figma.com/file/YjhpzSsYaZI5VOaamsvIku/Telerik-%26-KENDO-UI-Kit-for-Bootstrap-1.9--(UNPUBLISHED)?node-id=4695%3A221497) from $gray-100 to $component-bg as it should reuse the Card's header.

**Comment by epetrow** [comment]
Done
