### ISSUE TITLE
ContextMenu is not scrollable

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-themes#2961]
**Describe the regression**
ContextMenu is not scrollable. The arrow for scrolling is missing.

**To reproduce**

1. Open in Dojo the [scrollable](https://docs.telerik.com/kendo-ui/api/javascript/ui/contextmenu/configuration/scrollable) example in the ContextMenu API
1. Right-click to see the ContextMenu

**Expected behavior**
The ContextMenu should be scrollable with SASS themes when the scrollable option is enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/14364791/141467599-5aab293d-84e4-445b-8de0-420edf6b454e.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Additional context**
Regression since version: 2020.2.513

**Comment by silviyaboteva** [comment]
I tested both versions - the working one, e.g. `2020.1.406` and noot working, e.g. `2020.2.513 (and newer)`. It seems that in themes, there are no changes. The issue is caused by the inline style `display: none` applied to the arrows. I'm attaching screenshots for reference:
**Before**
<img width="1123" alt="Screenshot 2022-01-06 at 11 01 31" src="https://user-images.githubusercontent.com/17604855/148358685-2d2ab804-83a0-4f82-ad8d-fc3d5e14d596.png">
**After**
<img width="1151" alt="Screenshot 2022-01-06 at 11 05 00" src="https://user-images.githubusercontent.com/17604855/148358715-5b164bbc-e584-439a-898b-2e21c34ed238.png">

@nelito987 can you check with a developer what might be changed in `2020.2.513` of the widget implementation? And if you confirm that this is a bug in the widget, please transfer it.

**Comment by nelito987** [comment]
@silviyaboteva after a discussion with a developer from the jQuery2 team the issue is now transferred to kendo-ui-core repo #telerik/kendo-ui-core/issues/6673 . Thus, I am closing this one.
