### ISSUE TITLE
DateTimePicker rtl incorrect display

### ISSUE THREAD

**Issue by IKKI2000** [telerik/kendo-themes#3091]
**Describe the bug**
DateTimePicker rtl incorrect display.

**To reproduce**
See [dojo](https://dojo.telerik.com/eKugEmUc)

1. Click 'Run'
2. You can see blank on the left

**Expected behavior**
DateTimePicker rtl correct display.

**Affected package**
* All

**Affected suites**
* Kendo UI for jQuery

**Affected browsers**
* All

**Comment by joneff** [comment]
This issue is targeted in v5 kendo-themes, which will be released in early January, 2022. (The suites, kendo-jquery in particular, will be released in mid January to give is time to properly test everything!)

As the name suggests, v5 is a major change and there will be some incompatible changes, although, the main goal is to keep the visual appearance of the components as much as possible.

**Comment by joneff** [comment]
fixed by 9d98b62cd6b8ce69c0e00fd17381da8851ef450f
