### ISSUE TITLE
PivotGridV2 issues related to the new styling options

### ISSUE THREAD

**Issue by MilenaCh** [telerik/kendo-themes#3226]
- [ ] Chip appearance does not follow the design(https://kendobuild-windows.dev.progress.com/kendo-ui-next/pivotgridv2/index):
   Expected:
![design](https://user-images.githubusercontent.com/3844466/149338662-2e14b648-f74a-4287-961e-ae8885b533ce.PNG)
Actual:
![actual](https://user-images.githubusercontent.com/3844466/149338696-dd6fee90-d2da-431c-99fe-11f3cbc37d54.PNG)

- [ ] There is no spacing between the dropdown and input in the filter menu(https://kendobuild-windows.dev.progress.com/kendo-ui-next/pivotgridv2/index):
 ![spacing](https://user-images.githubusercontent.com/3844466/149339248-c0ed7a33-40af-4dc4-8eed-bff61d59235c.PNG)

**Comment by silviyaboteva** [comment]
Hey @MilenaCh,

1. About the Chip, as the property `rounded` is `medium` by default (reference: https://github.com/telerik/kendo-themes/issues/2935). This is expected. In order to render fully rounded chips in the PivotGrid, please set the `rounded` option to `full` in the implementation of the widget.

2. The issue is comming by the fact that there is an additional `div` element in the `k-filter-menu-container`. Check the screenshot below:
<img width="462" alt="Screenshot 2022-01-14 at 14 55 11" src="https://user-images.githubusercontent.com/17604855/149519137-fbc864d9-df95-42b5-8705-bab876f27139.png">

Once removed:
<img width="452" alt="Screenshot 2022-01-14 at 14 59 59" src="https://user-images.githubusercontent.com/17604855/149519266-b730e0a9-5851-4dc5-bb6c-0603f18c7591.png">

The output will be as expected:
<img width="237" alt="Screenshot 2022-01-14 at 15 00 48" src="https://user-images.githubusercontent.com/17604855/149519333-a1cb8895-480f-4495-b4fe-eb13a2d94931.png">

May I ask you to transfer this issue to the dev team?

**Comment by MilenaCh** [comment]
@silviyaboteva yes, I've created a similar [issue ](https://github.com/telerik/kendo/issues/14312)in kendo repo.
Thank you!
