### ISSUE TITLE
$notification-themes map cannot be modified

### ISSUE THREAD

**Issue by JoomFX** [telerik/kendo-themes#3341]
**Describe the bug**
With the [current implementation](https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/notification/_variables.scss#L32) it is not possible to modify the values in the `$notification-themes` map.
Currently, the user needs to modify the `$kendo-theme-colors` map in order to see the changes in the `$notification-themes` map but this might bring unwanted results as well.
For reference - ticket 1551122.

**Expected behavior**
Users should be able to modify the values in the `$notification-themes` map directly.

**Screenshots**
N/A

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment]
The issue is now resolved, which is visible by the status. Here is how we solved it:

* we now respect existing maps by using `!default` flag;
* we have a separate map for notification color and we'll also respect that, if it exists;
* we provide an additional function `notification-theme` (although it may be renamed at some point to `kendo-notificatoin-theme` if we deem the approach fit) to further customize how colors are transformed.

You could say it's a bit of over engineering on our part, which it may be, but is also future forward allowing multiple plug points for customisation.

**Comment by meriturva** [comment]
@joneff  Are you going to release a version before 2022.2 with that fix?
