### ISSUE TITLE
Responsive Toolbar does not behave as expected in flex layout 

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-themes#3428]
**Describe the bug**
Having a [responsive ToolBar ](https://www.telerik.com/kendo-angular-ui/components/toolbar/responsive-toolbar/) in a flex layout does not behave as expected when the container size is changed. 

Check the following screencast and notice how the Responsive Toolbar behaves:
https://screenrec.com/share/l5re3REo8P

**To reproduce**
https://stackblitz.com/edit/angular-thjs7u-yc8ecx

1. Drag the splitter of the StackBlitz to reduce the width of the demo

**Expected behavior**
The items in the toolbar should be truncated when necessary, instead of pushing the container on the right.

**Additional context**
I noticed that `flex-wrap: nowrap` is set to the ToolBar when the responsible feature is enabled. Setting it to `flex-wrap: wrap` seems to do the trick:
https://stackblitz.com/edit/angular-thjs7u-erzz83

but there are cases when the ToolBar is not calculating its width correctly and the items are rendered under each other:
![image](https://user-images.githubusercontent.com/33104481/156123588-14a812a5-01b3-4c42-be13-c10976d57f00.png)

**Comment by epetrow** [comment]
I don't think that this is an issue with the themes/component, but rather with how it is being used.

In the demo the responsive toolbar is wrapped in a flex container and in flex context the min-width of flex items is set to `auto,` which can make elements take up more space than needed, resulting in overflow.

For this particular case adding `min-width: 0` on the responsive toolbar's wrapper with class `.left` seems to produce the expected behavior. 

Here is an example: [https://stackblitz.com/edit/angular-thjs7u-svcjcs](url)
