### ISSUE TITLE
DateTimePicker popup is opened by clicking exactly on the icon 

### ISSUE THREAD

**Issue by VicTachev** [telerik/kendo-themes#363]
If the area next to the icon is clicked the popup is not opened. It should be possible to open the popup by clicking next to the icon.

![image](https://user-images.githubusercontent.com/11771009/46859043-588beb80-ce15-11e8-9b50-694f56561a10.png)

Reported in ticket 1346096

**Comment by joneff** [comment]
This is not a theme issue, but a JS one -- the events are attached to the icons, instead of the containing span elements, as visible from the code and the screenshot the customer submitted

![image](https://user-images.githubusercontent.com/8048/46880006-32d00800-ce50-11e8-977a-940873f6fcda.png)

 I've already logged it https://github.com/telerik/kendo-ui-core/issues/4551
