### ISSUE TITLE
High contrast CSS for the Combobox

### ISSUE THREAD

**Issue by jrmcdona** [telerik/kendo-themes#3659]
Hey all, I am trying to fix accessibility at Microsoft where high contrast is required for us.  We had this working but then we updated Kendo versions and the selectors of the combo box changes and now this no longer works.

Here is a pic of the combo box.   As you scroll through the background of the item selecte should have the windowtext background.
![image](https://user-images.githubusercontent.com/4327773/174396894-12cd3ff2-8de8-4dc2-8cf1-a52c03edd762.png)

This was working with an old version of Kendo:

@media all and (-ms-high-contrast: active) {
  .k-button:focus,
  .k-toolbar .k-button-icon:focus,
  .k-picker-wrap:focus,
  .k-dropdown-wrap:focus {
    outline: 2px solid windowText !important;
  }
}

Can I get help with the new selectors?

**Comment by TeyaVes** [comment]
Hello @jrmcdona , the problem here is that the MS High Contrast mode adjusts the elements styling and in some cases (as the case with the span) there isn't an easy way to override these default colors and backgrounds. An option would be 'turning off' this High Contrast adjustment by adding the following property:

`forced-color-adjust: none;`

to the inner span once the .k-list-item is hovered.

Please, let me know if this would work for you.
