### ISSUE TITLE
Scheduler Theme Problem

### ISSUE THREAD

**Issue by vzsoft** [telerik/kendo-themes#3754]
**Describe the bug**
i use
`kendo.common-bootstrap.min.css`
`kendo.default-v2.min.css (for k-icon k-i-gear k-icon-xl)`
`kendo.highcontrast.min.css`

now Scheduler Background color and text color of days in a week  and alldays are white

also this problem exist in following themes
`Highcontrast,Black,MetroBlack,Moonlight`

**To reproduce**
1. Go to [Dojo](https://dojo.telerik.com/@vzsoft/usUFUcIy)
2. See Background and Text Color days in a week and alldays are white

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-classic

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* OS: Windows 10

thank you

**Comment by TeyaVes** [comment]
Hello @vzsoft , you are experiencing the following issue because the Kendo themes are not properly imported in the example. 

If you are using a SASS-based theme- default, bootstrap, material, classic, you don't need to import the kendo.common-bootstrap.min.css and kendo.highcontrast.min.css. For example, if you want to use the dark swatch from the SASS default theme, you should import only:
**kendo.default-main-dark.min.css**

On the other hand, if you wish to use the high contrast LESS theme, you should include:
**kendo.common.min.css** and **kendo.highcontrast.min.css**

You can check the following articles for more information:
[https://docs.telerik.com/kendo-ui/styles-and-layout/less-themes/overview#adding-a-theme-to-your-project](https://docs.telerik.com/kendo-ui/styles-and-layout/less-themes/overview#adding-a-theme-to-your-project)

[https://docs.telerik.com/kendo-ui/styles-and-layout/sass-themes/installation#using-pre-built-css](https://docs.telerik.com/kendo-ui/styles-and-layout/sass-themes/installation#using-pre-built-css)
