### ISSUE TITLE
Implement Material for Dropdownlist - Kendo UI

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-themes#40]
related telerik/kendo#8250

**Comment by Dimitar-Goshev** [comment]
- [ ] Server filtering textbox is not styled as Text field box - https://material-components-web.appspot.com/text-field.html
- [ ] Not vertically centered server filtering icon:
![image](https://user-images.githubusercontent.com/6614183/37156975-2f5cccc8-22f0-11e8-904e-99c3682529fa.png)
- [ ] Bottom border width should become 2px on hover
- [ ] Bottom border of disabled DropDownList is not dotted
- [ ] The expand arrow of DropDownList does not change its direction upwards in expanded state.
- [ ] The expand arrow of invalid DropDownList (class k-state-invalid added) is red, but by design its color should not change - same as ComboBox:
![image](https://user-images.githubusercontent.com/6614183/37155958-572d6332-22ed-11e8-9181-bb3f990dbee4.png)
- [ ] If an invalid DropDownList (class k-state-invalid added) is hovered, the normal hover state is applied - bottom border is not red anymore. Should it be "hover invalid" state instead - 2px red bottom border?
- [ ] Displaced loading icon, similar to AutoComplete:
![image](https://user-images.githubusercontent.com/6614183/37153371-35b097ae-22e5-11e8-8a0d-eff8657fb89c.png)
- [ ] Grouping - missing design - [logged for implementation](https://github.com/telerik/kendo/issues/7946)

**Comment by mvgmvg** [comment]
Waiting for missing design for grouping implementation to close the issue.

**Comment by Dimitar-Goshev** [comment]
- [ ] Grouping header is not all caps and it should be higher than other items - design:
![image](https://user-images.githubusercontent.com/6614183/38561289-55e040dc-3ce0-11e8-9055-2e7c3655e19a.png)
- [ ] RTL - Loading icon is not on the left:
![image](https://user-images.githubusercontent.com/6614183/38564823-92c18e86-3ce8-11e8-895e-9b4a04140abf.png)

**Comment by Dimitar-Goshev** [comment]
- [ ] Server filtering textbox is not styled as Text field box - https://material-components-web.appspot.com/text-field.html - **Still not following design below**:
![image](https://user-images.githubusercontent.com/6614183/38565934-393ec092-3ceb-11e8-9806-b137f3fd514b.png)
- [ ] Not vertically centered server filtering icon - currently OK, butto be retested after implementing point above:
![image](https://user-images.githubusercontent.com/6614183/37156975-2f5cccc8-22f0-11e8-904e-99c3682529fa.png)
- [ ] Server filtering icon does not change its place in RTL.
- [ ] Group tags are not swapped in RTL (All SASS themes):
![image](https://user-images.githubusercontent.com/6614183/38567380-bb422c5c-3cee-11e8-8dc9-34d21d9e5e4b.png)
