### ISSUE TITLE
[FlatColorPicker] Focus each component complying with A11Y KB navigation

### ISSUE THREAD

**Issue by PaskalevStoyan** [telerik/kendo-themes#4039]
This is related to: https://github.com/telerik/k2/issues/843 and more precisely the FlatColorPicker component. 

After a discussion with @imasyuko and her discussion with the design team, we've agreed that the following design should be followed when coming to focused inner components:

[default](https://www.figma.com/file/3fta3SPx6nJMPTUcHTKmNI/Telerik-%26-KENDO-UI-Kit-Default-2.2-(UNPUBLISHED)?node-id=0%3A1)
[bootstrap](https://www.figma.com/file/YjhpzSsYaZI5VOaamsvIku/Telerik-%26-KENDO-UI-Kit-for-Bootstrap-2.2--(UNPUBLISHED)?node-id=0%3A1)
[fluent](https://www.figma.com/file/ezWHkvf2S0yalmqLQzu6Ed/MS-Fluent?node-id=7%3A3489)
[material](https://www.figma.com/file/Bun5XXsG0UuzCMz5GyDoHK/Telerik-%26-KENDO-UI-Kit-for-Material-2.2--(UNPUBLISHED)?node-id=0%3A1)

**Comment by imasyuko** [comment]
Hey everyone. Links are updated as the designs were moved from the UI kits to the internal files. There are technical limitations in Figma when it comes to borders (applying offset is one of them), so to achieve this type of focused border effects were used. That's why the borders are not dotted.

https://www.figma.com/file/gWUIux95BHxemqWwOw9ZwB/Default-Theme---Internal-Usage?node-id=7627%3A279493
https://www.figma.com/file/k8eCVo9JZeHZlV9o8SXZtd/Bootstrap-Theme---Internal-Usage?node-id=2418%3A175444
https://www.figma.com/file/qpaRti273eNVEEOYOUxojT/Material-Theme---Internal-Usage?node-id=2138%3A171133
https://www.figma.com/file/qpaRti273eNVEEOYOUxojT/Material-Theme---Internal-Usage?node-id=2138%3A171133
