### ISSUE TITLE
Scheduler Timeline view misaligned with slot templates

### ISSUE THREAD

**Issue by CecoMilchev** [telerik/kendo-themes#4071]
When a Scheduler is used that has a Slot Template, the cells in the Timeline view are misaligned. The content of the slot template expands the cell.

1. Create a Scheduler, add resources, and group by resources.
1. Set a slot template - add content to the cells.
1. Navigate to the Timeline view - the cells are misaligned.

Dojo for reproduction https://dojo.telerik.com/isapodaX

It appears that the k-scheduler-cell and k-grouping-cell have both flex-basis CSS rule that causes the misalign.

**Affected package (please remove the unneeded items)**
* theme-default

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable
* OS: Windows

**Comment by epetrow** [comment]
Since `flex-basis: auto` needs to be applied to the `k-scheduler-cell` due to a specific scenario in React ( showcased [here](https://github.com/telerik/kendo-themes/issues/2497) ), our proposition would be to absolutely position the slot template by utilizing `!k-pos-absolute` from the utility classes if needed. I've added a test in the linked PR to illustrate this.
