### ISSUE TITLE
Sorting icon is not visible when header text overflows

### ISSUE THREAD

**Issue by inikolova** [telerik/kendo-themes#410]
Sorting icon is not visible when header text is long but the column width is small. Can be observed in the Master-Detail Grids demo -> http://www.telerik.com/kendo-angular-ui/components/grid/hierarchy/

To reproduce the issue sort the CategoryID column

**Comment by vsviridov** [comment]
> A workaround for this issue is to move the sort indicator icon before the header text, for example with the following rule:

Does not work correctly with multi-sort...
![image](https://user-images.githubusercontent.com/221684/50869094-7f4fb480-1367-11e9-8018-b7f57ec345d5.png)

**Comment by vsviridov** [comment]
Not sure why the un-assignment happened, that was not the intention of the comment...

**Comment by TeyaVes** [comment]
A possible workaround would be:

```
 .k-grid-header .k-header>.k-link {
        padding-right: 1.5em;
}

.k-grid-header .k-header>.k-link>.k-icon {
        position: absolute;
        top: 50%;
        right: 0.5em;
        transform: translateY(-50%);
        margin-left: 0;
}

.k-grid-header .k-sort-order {
        position: absolute;
        right: 0.25em;
}
```
Live example here: [https://stackblitz.com/edit/angular-x8dpcl](https://stackblitz.com/edit/angular-x8dpcl)
In this way, the sorting icon and the number will be aligned to the right of the cell:


![2019-03-25_1107](https://user-images.githubusercontent.com/45764088/54907478-41861500-4eee-11e9-9e4e-19d52a6635d9.png)

@joneff @lkarakoleva , what do you think?

**Comment by DaleyKD** [comment]
@TeyaVes : That's the best one yet.  However, it does look a bit odd with the filter icon, and if filtering is enabled, you can't see it.

I can't believe this hasn't been resolved yet.  I'm using 3.4.0

**Comment by jadamrogers** [comment]
I ran across this post specifically because I was having this issue and wanted to move the sort indicator and number to the left side of the header text. After much work, I found a very good solution that only requires CSS.

`
/* sort icon color */
.k-grid-header .k-header > .k-link > .k-icon:before {
    color: #f2b661;
}
/* sort order number color */
.k-grid-header .k-header > .k-link > span.k-sort-order {
    color: #f2b661;
}

/* move sort icon and number to left and shift text right to make room for them when a column is sorted */
.k-grid-header th.k-header.k-sorted > .k-link {
    position: relative;
    padding-left: 18px;
}
.k-grid-header .k-header.k-sorted > .k-link > .k-icon.k-i-sort-asc-sm,
.k-grid-header .k-header.k-sorted > .k-link > .k-icon.k-i-sort-desc-sm {
    position: absolute;
    top: 7px;
    left: -12px;
}
.k-grid-header .k-header.k-sorted > .k-link > .k-sort-order {
    position: absolute;
    top: 6px;
    left: 10px;
}
`
You might need to play with the numbers a little bit based on your font sizing in the grid, but this will do what you want.
