### ISSUE TITLE
Editor's View HTML dialog is not high enough to show its content

### ISSUE THREAD

**Issue by Dimitar-Goshev** [telerik/kendo-themes#416]
URL: kendo-ui/editor/all-tools
Click on View HTML button. All browsers are affected, however, there is a resize handle in FF and Chrome to show all the content.

![image](https://cloud.githubusercontent.com/assets/6614183/25392283/f24bf7b8-29e0-11e7-8ce1-f5ceab74dc3f.png)

**Comment by Dimitar-Goshev** [comment]
@joneff The issue is still reproducible on live https://demos.telerik.com/kendo-ui/editor/all-tools as well as on themes dev channel staging.

**Comment by Juveniel** [comment]
The issue is reproducible only with the Kendo jQuery Editor which has a different rendering, as it uses Window for its tools popups instead of a Dialog. Thus, the action buttons (Update and Cancel) are rendered inside the content element and make it difficult to achieve [the design guidelines](https://github.com/telerik/kendo-ux/blob/master/themes/default/PNG/editor.png) for the Editor Dialogs. This also causes the action buttons to look different.

In order to resolve the issue, the Editor implementation must be changed to utilize Dialogs for its tools popups. This will allow the action buttons to be placed below the content element and increase the textarea height accordingly. 

Taking the above into consideration, the issue will be targeted in Kendo jQuery with [the following PR](https://github.com/telerik/kendo/pull/10671).
