### ISSUE TITLE
Implement Material for ComboBox - Kendo UI

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-themes#44]
related telerik/kendo#8250

**Comment by Dimitar-Goshev** [comment]
- [ ] Bottom border width should become 2px on hover
- [ ] Bottom border of disabled ComboBox is not dotted
- [ ] The expand arrow of ComboBox does not change its direction upwards in expanded state.
- [ ] The expand arrow of invalid ComboBox (class k-state-invalid added) is red, but by design its color should not change:
![image](https://user-images.githubusercontent.com/6614183/37155958-572d6332-22ed-11e8-9181-bb3f990dbee4.png)
- [ ] If an invalid ComboBox (class k-state-invalid added) is hovered, the normal hover state is applied - bottom border is not red anymore. Should it be "hover invalid" state instead - 2px red bottom border?
- [ ] Displaced loading icon, similar to AutoComplete:
![image](https://user-images.githubusercontent.com/6614183/37153371-35b097ae-22e5-11e8-8a0d-eff8657fb89c.png)
- [ ] Grouping - missing design - [logged for implementation](https://github.com/telerik/kendo/issues/7946)

**Comment by mvgmvg** [comment]
Waiting for missing design for design of grouping implementation to finish the issue.

**Comment by Dimitar-Goshev** [comment]
- [ ] Grouping header is not all caps and it should be higher than other items - design:
![image](https://user-images.githubusercontent.com/6614183/38561289-55e040dc-3ce0-11e8-9055-2e7c3655e19a.png)
- [ ] RTL - Loading icon is not on the left:
![image](https://user-images.githubusercontent.com/6614183/38564851-a386b80e-3ce8-11e8-80bc-99a11a3cd24f.png)

**Comment by Dimitar-Goshev** [comment]
- [ ] Group tags are not swapped in RTL (All SASS themes): - **Still reproducible**
![image](https://user-images.githubusercontent.com/6614183/38567380-bb422c5c-3cee-11e8-8dc9-34d21d9e5e4b.png)
