### ISSUE TITLE
Calendar next and back buttons icon RTL not correctly

### ISSUE THREAD

**Issue by vzsoft** [telerik/kendo-themes#4461]
**Describe the bug**
Calendar next and back buttons icon RTL not correctly

**To reproduce**
1. Create kendo Calandar with RTL [DOJO](https://dojo.telerik.com/@vzsoft/UjifuZiK)
2. Run Query
4. Arrow Icon Not Correct

**Screenshots**
![rtl](https://user-images.githubusercontent.com/5305981/235722284-4f1f9a69-1e2e-47c0-8998-792c24769832.jpg)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* OS: [Windows 10]

**Comment by inikolova** [comment]
This issue is caused by we are currently flipping the arrow icons in RTL. However, after internal discussions we decided that the correct approach would be replacing the icons in the rendering with their left/right equivalent and removing the flipping styles from the themes. Below is the corresponding PR in the themes:
https://github.com/telerik/kendo-themes/pull/4481
 
The rendering changes in the Calendar component will be available in the next official version of Kendo UI for jQuery.
