### ISSUE TITLE
Implement Material for Multiselect - Kendo UI

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-themes#45]
related telerik/kendo#8250

**Comment by Dimitar-Goshev** [comment]
- [ ] Hovered token does not change its background
- [ ] Margins around token Close button are incorrect. By design they are left 6px and right 4px, but it is implemented as left 7px and right 6px. Thus there is too much space to the right between the button and the right side of the token, compared to above and below the button:
![image](https://user-images.githubusercontent.com/6614183/37157625-01411374-22f2-11e8-852a-754db1a1d226.png)
- [ ] Bottom border width should become 2px on hover
- [ ] Bottom border of disabled ComboBox is not dotted
- [ ] k-state-invalid does not change the border color
- [ ] No focus indicator for focused dropdown item

**Comment by mvgmvg** [comment]
Waiting for design for grouping implementation to finish the issue.

**Comment by Dimitar-Goshev** [comment]
- [ ] Grouping header is not all caps and it should be higher than other items - design:
![image](https://user-images.githubusercontent.com/6614183/38561289-55e040dc-3ce0-11e8-9055-2e7c3655e19a.png)
- [ ] LTR - Loading icon does not cover the clear icon completely. It is possible to click the clear icon. (Use Server filtering demo -> stop internet in Chrome -> type a in input:
![image](https://user-images.githubusercontent.com/6614183/38563591-e842a078-3ce5-11e8-9ef2-c8fc76e0b8ed.png)

- [ ] RTL - Loading icon does not cover the clear icon (x):
![image](https://user-images.githubusercontent.com/6614183/38563168-e451f9ec-3ce4-11e8-9dda-a48bf73545ca.png)

- [ ] RTL - Wrong horizontal margins between tokens, wrong vertical margins (RTL and LTR), displaced delete circle:
![image](https://user-images.githubusercontent.com/6614183/38563304-2bb7d248-3ce5-11e8-98e4-bec5015d5731.png)

**Comment by Dimitar-Goshev** [comment]
- [ ] Wrong padding of Group header in RTL:
![image](https://user-images.githubusercontent.com/6614183/39121496-7e4fccda-46fa-11e8-90e1-6e877d2543a3.png)

NOTE: Not reproducible in all cases, e.g. on the demo it is reproducible, if you type a, but not reproducible, if you type z.

**Comment by mvgmvg** [comment]
This is JavaScript issue not related to implementing the Material theme. I have logged the issue here https://github.com/telerik/kendo/issues/8415
