### ISSUE TITLE
Incompatible units error occurs when default or material theme is used with Bootstrap

### ISSUE THREAD

**Issue by kakone** [telerik/kendo-themes#451]
An incompatible units error occurs when the SCSS of the default theme or the material theme is used with Bootstrap :

> Incompatible units: 'rem' and 'px'.
> in \node_modules\bootstrap\scss\_variables.scss (line 448, column 41)

## Environment
Package versions:
- @progress/kendo-theme-default@2.60.0 or @progress/kendo-theme-material@1.5.0
- bootstrap@4.1.3

**Comment by joneff** [comment]
Can you share more information on how the issue has manifested? For instance, how does your sass file look?

I am asking for more information, because we specifically check that our variables are compatible with bootstrap -- https://github.com/telerik/kendo-themes/blob/develop/packages/default/build/twbs-compat.scss. To provide even more context, if that file fails to build, we won't be able to make a new release, or merge a branch. In other words, it's a safeguard for compatibility with bootstrap (in terms of variables).

**Comment by kakone** [comment]
My mistake, in my sass file, I imported the bootstrap files after the kendo one.
