### ISSUE TITLE
Implement Material for Tooltip - Kendo UI

### ISSUE THREAD

**Issue by mvgmvg** [telerik/kendo-themes#49]
related telerik/kendo#8250

Guidelines:
https://material.io/guidelines/components/tooltips.html#tooltips-interaction

**Comment by Dimitar-Goshev** [comment]
@mvgmvg Please review the comments on the pull request and resolve any issues there. Also note that the Splitter styles went there unexpectedly.

**Comment by Dimitar-Goshev** [comment]
- [ ] Closable tooltip is higher than a non-closable. Also its text is bigger and the close icon is displaced:
![image](https://user-images.githubusercontent.com/6614183/37467318-8f74b51c-2868-11e8-9e7a-e9ea4a160d99.png)

- [ ] Ajax and Content template demos - tooltips flicker, as their content goes out of the tooltip and may be hovered. The issue is reproducible with Bootstrap v4 as well - https://demos.telerik.com/kendo-ui/tooltip/ajax and https://demos.telerik.com/kendo-ui/tooltip/template - [video](https://www.screencast.com/t/1Fm1rpxtGT)

**Comment by Dimitar-Goshev** [comment]
- [ ] Tooltip callout is not centered in all themes - it will become a regression, if not fixed for R2:
![image](https://user-images.githubusercontent.com/6614183/39231043-6d4e49fc-4871-11e8-8781-a3daf43e752d.png)
