### ISSUE TITLE
Content in inline editor is wrapped when its font style is changed

### ISSUE THREAD

**Issue by nelito987** [telerik/kendo-themes#5187]
**Describe the bug**
When the user selects a word and changes its style (for example bold, italic, etc.) the content of the inline Editor is wrapped on multiple lines.

**To reproduce**

1. Go to Dojo - https://dojo.telerik.com/JNAQLLsy
2. Select a word in the editor and change its style from the tools.

**Expected behavior**
The content should not wrap.

**Screenshots**
![image](https://github.com/user-attachments/assets/00e11a1c-d840-4b56-b5a8-f793783d5d24)

**Workaround**
```
<style>
      .k-editor{
        display: block
      }
</style>
```
Dojo - https://dojo.telerik.com/iZZPZIGg

**Regression since 2022.1.119**

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Comment by epetrow** [comment]
@nelito987, this does not look like a themes related issue to me. The problem (as far as I understood) only occurs in the scenario when you have a plain text node as the content of the Editor. If the content is text and is wrapped in any valid HTML element (e.g. `<span>, <p>`) the issue is not reproducible. Furthermore other suites seem to "enforce" wrapping plain text inside a paragraph if it is passed as the content, for [example](https://stackblitz.com/edit/react-ykv1nk?file=app%2Fapp.jsx).
