### ISSUE TITLE
Clear button in kendo-combobox is displayed on top of dropdown toggle in IE11

### ISSUE THREAD

**Issue by noariki** [telerik/kendo-themes#546]
## I'm submitting a...
* Regression report 

## Current behavior
Clear button in kendo-combobox is displayed on top of dropdown toggle in IE11 when compiling styles from the package. IE doesn't support nested calc.

## Expected behavior
Clear button in kendo-combobox to be displayed to the left from dropdown toggle in IE11

## Minimal reproduction of the problem with instructions
Open following example in IE11. Switch to kendo-default-theme@2.62.0 for correct behavior.
https://angular-scss-demo-sq3ndb.stackblitz.io
https://stackblitz.com/edit/angular-scss-demo-sq3ndb

## Environment
Product:
* Kendo Ui for Angular

Browser:
- IE version 11

**Comment by GlenCroft** [comment]
Issue still exists with @progress/kendo-theme-default@4.1.0
[https://angular-f7uxyn-szfolc.stackblitz.io](https://angular-f7uxyn-szfolc.stackblitz.io)
[https://stackblitz.com/edit/angular-f7uxyn-szfolc](https://stackblitz.com/edit/angular-f7uxyn-szfolc)

**Comment by GlenCroft** [comment]
I found a workaround fix if you override the SASS variable with:
`$picker-select-size: #{$picker-select-line-height * 1em} + #{$picker-select-padding-y * 2};`

Be careful though, this only currently works because everywhere that uses $picker-select-size does wrap it with `calc()`. The problem is we're ending up with a nested `calc( calc(...) ...)` which IE doesn't like.
