### ISSUE TITLE
Switch labels not visible for dark default theme

### ISSUE THREAD

**Issue by Snupss** [telerik/kendo-themes#677]
## I'm submitting a...
* Bug report

## Current behavior
Switch always has white background when off (Default theme), which makes label unreadable for dark themes.

## Expected behavior
Off label to have theme consistent background color.

## Minimal reproduction of the problem with instructions
Navigate to https://themebuilder.telerik.com/kendo-angular-ui
Start Theming -> Default -> Choose "Moonlight" Or "Metro Black" swatch.
Turn switch off

## What is the motivation or use case for changing the behavior?
To have a consistent theme for the switch control

## Environment
Product:
* Kendo Ui for Angular

Browser:
- Chrome (desktop) version XX

**Comment by simonssspirit** [comment]
They are not visible for the Bootstrap and Material themes in KendoReact as well:

https://www.telerik.com/kendo-react-ui/components/inputs/switch/labels/

**Comment by eeasss** [comment]
This is probably intended and result of a design decision. See here https://www.telerik.com/kendo-angular-ui/components/inputs/switch/labels/ and material design recommendation here: https://material.io/design/components/selection-controls.html#switches

@lkarakoleva or @ivelina-penkova can you comment?

**Comment by ivelina-penkova** [comment]
@eeasss The behavior in the theme builder observed in the Moonlight and Metro Black swatches is certainly not by design. In fact the behavior by design could be seen in the themes here : https://demos.telerik.com/kendo-ui/switch/index

There is a problem in the theme builder and that's why the OFF label is not visible but it's there. 

I see you have linked the bootstrap design and you have referred to the Material guidelines and yes, we have a case of the switch having no labels at all and that is by design. We allow the option of choosing whether the switch has labels or not. However, there is no case of having the ON label but having no OFF label.

cc: @PreslavKozovski  @lkarakoleva

**Comment by eeasss** [comment]
Yes, Iva thanks for the clarification. My comment referred to to the second issue added by Stefan. We addressed this by adding an appropriate description in the switch label demo.
The original problem with the default theme and the theme builder persists.
