### ISSUE TITLE
Bootstrap 4 validation doesn't show up.

### ISSUE THREAD

**Issue by cornillemichiel** [telerik/kendo-themes#68]
Bootstrap 4 altered the way validation works before going to RTM, in that it no longer uses 
has-warning has-error etc, but now supports both HTML5 pseudoclasses
:invalid and :valid

As a fallback for controls that don't set :invalid or :valid pseudoclasses we can set is-valid or is-invalid regular CSS classes on the controls.

However, neither of those are reflected visually. **(no red/green border + outline is shown)** around the control.

Secondary, when entering the input field of a combobox, it does wrongly show an outline on that one.

I tried setting the is-invalid class on the **combobox** (which also has the form-control class) and I also tried to call setCustomValidity from javascript on the inner input of the combobox, which already got rid of the wrongly displaying green outline and replaced it with the correct RED outline.

We are not using kendo validation at the moment, as we already have a validation framework in place (aurelia-validation + bootstrap styling)

**Comment by joneff** [comment]
While we use Bootstrap theme as a set of variables, we do not adhere to its class name scheme.

Still you are right when pointing out that the visual cue of validation result is no properly applied. We've partially covered the fix by removing `:invalid` selector, so we can apply a class name when needed. We've also added styles for the said class names. I've added a related issue in the kendo repo, since the issue now is, technically speaking, related to the kendo code, as we need to add / remove classes to specific elements.

**Comment by ntimmerman** [comment]
So like, when's that gonna happen?

**Comment by DaleyKD** [comment]
I'm glad to see this is on the roadmap.

I'm purposefully trying not to use the kendo validator, since I only use kendo controls sparsely.  However, what a pain today was trying to get a DateTimePicker to work with jQuery Validation + Unobtrusive.

I finally figured it out, but getting styles to work with Bootstrap 4 was a lot harder than it should be.
![image](https://user-images.githubusercontent.com/7206282/77358621-2c69df00-6d18-11ea-9861-5cc32c5c94f3.png)

I'm having to apply `.k-invalid` to the `.k-picker-wrap` div, and `.is-invalid` to the `.k-widget` and `.k-input` divs.  That still doesn't fix everything, such as the background-image icon.  I'm sure Kendo has their own.

If `.k-datetimepicker .k-picker-wrap .k-input` didn't override `background`, `border`, and `outline`, then I could probably get away with just having `.is-invalid` on the `.k-input`.

**Comment by joneff** [comment]
We ironed out **most** of the quirks regarding our **visual** differences with Bootstrap.

There is also some recent development: we'll be refactoring all inputs in all suites to allow a more granular way of customization. In doing that, we'll move all relevant state classes to the top most element. One of those class names being `k-invalid`, which would result in the following consistent selectors:

```css
.k-combobox.k-invald { ... }
.k-datetimepicker.k-invald { ... }


.k-combobox.k-invald:focus-within { ... }
.k-datetimepicker.k-invald:focus-within { ... }
```

The change will allow to apply top level class names that could override our styles, provided they specificity greater or equal to 0 2 0. For the focus state the specificity should be greater or equal to 0 3 0.

That being said, the structural differences between us and Bootstrap remain:

Bootstrap validation is not designed to be applied on anything else but pure inputs / selects. In other words adding `form-control is-invalid` to combobox or autocomplete or anything else will not have the expected effect -- https://dojo.telerik.com/@joneff/EWexeyoC.

There is sort of workaround: by changing the order of the styles (putting bootstrap styles first) some of the layout issues will be solved. But then we have other... like the padding... Removing that causes yet another issue: the validation icon is now beneath the clear icon of the autocomplete and the dropdown part of the combo -- https://dojo.telerik.com/@joneff/ECuvIQeY. Try uncommenting some styles.

Say we do another fix to place the icon slightly to left. So far, so good, but the clear icon of the combo, autocomplete and other components is a setting, so we should compensate for that as well...

Then there is RTL, so we should compensate for that. Yes, there is `inset-inline-end`, but it's not as readily available, as we would like it to be.

Finally, some of our components have their own validation icons and that makes the case even harder.

So here is what we could sanely do with the aforementioned refactoring of our components:
* mitigate the padding part and layout part of `.form-control`
* remove the background image for the validation of `.form-control.is-valid` and `.form-control.is-invalid`

Additionally:
* open a PR in Bootstrap to use `display: flex` 
* open a PR in Bootstrap to use `:focus-within` styles, so focus styles are applied correctly

How does it sound to you?
