### ISSUE TITLE
Material Theme - Input's underscore misaligned, obvious if next to other controls like NumericTextBox

### ISSUE THREAD

**Issue by Xizario** [telerik/kendo-themes#698]
Underlining is misaligned between Input and other input field types when using material scheme.
<img width="1379" alt="Screenshot 2019-04-18 at 8 38 20" src="https://user-images.githubusercontent.com/9458606/56339119-7f0c5400-61b5-11e9-8b24-e88092083e19.png">

Originally reported here: https://github.com/telerik/kendo-react/issues/234

Visible in this demo: https://www.telerik.com/kendo-react-ui/components/inputs/floating-labels/ using the material theme.

@joneff is there an easy css fix for this, since the client is already testing for production?

**Comment by KeiBlag** [comment]
As a workaround, we can provide `border-top: 1px solid transparent;` styles of the `.k-numerictextbox .k-numeric-wrap`  element:
```css
.k-numerictextbox .k-numeric-wrap {
    border-top: 1px solid transparent;
}
```
[Here](https://stackblitz.com/edit/kendo-angular-inputs ) is a runnable StackBlitz example.

Once, the fix is available in the kendo-themes, we will update the status of the issue.

**Comment by KeiBlag** [comment]
The fix is available in the latest `dev` channel of the kendo-themes.
