### ISSUE TITLE
Expand default + boostrap + material themes to mobile widgets

### ISSUE THREAD

**Issue by jlchereau** [telerik/kendo-themes#749]
## SASS themes are so much better! Please generalize to Kendo UI Mobile Widgets

For us the primary benefit of Kendo UI was to offer a consistent framework across all platforms/devices and we have developed custom widgets that we use in web and mobile apps. Unfortunately, now that responsive widgets are taking over, the consistency is getting broken by themes.

SASS themes have considerably improved the design over LESS themes and their mobile themes. The use of responsive widgets (e.g. Grid) in mobile apps. makes it necessary to expand these kendo-themes to mobile widgets (Note that mobile widgets have not improved in 3 to 4 years and this should start with maintaining the consistency with updated SASS themes).

I have made an entry on the feedback portal: https://feedback.telerik.com/kendo-jquery-ui/1409976-improve-mobile-themes-and-mobile-widgets. **Please vote for it!**.

**Comment by jlchereau** [comment]
Any roadmap to expand SASS styles to mobile widgets (and drop the old less styles) for consistency between web, responsive and mobile widgets?

**Comment by jlchereau** [comment]
Really looking forward to it in v2021.1, Keep up the good work.

**Comment by joneff** [comment]
For 2021.1 we are adding bottom navigation, which corresponds to our mobile tabstrip. Looking at the components, I can see that only actionsheet and popover are not transferred.

For the other points, namely ETA of the above and dropping less themes, perhaps @bergenhem, who is our PM can clarify.

**Comment by joneff** [comment]
* For 2021 R2 we added action sheet.
* For 2021.R3 we are releasing popover

With that, there will be desktop class counterparts for all mobile widgets. closing!

**Comment by jlchereau** [comment]
And we simply have to entirely rewrite our Cordova mobile apps made with Kendo UI Mobile Widgets. Great roadmap Telerik!

**Comment by bergenhem** [comment]
Hey everyone! I just want to jump in here and provide some additional clarity and context since this item does brush up on some larger items related to the Kendo UI Mobile-specific set of UI components.

First, some background for anyone stumbling upon this item. "Kendo UI Mobile" refers to a suite of UI components as well as framework items to help build SPA-type applications targeting primarily Cordova. These are mobile-specific UI components that also came with a set of LESS-based themes that replicated the look and feel of native elements across iOS, Android, and even Windows Phone just through LESS and the resulting CSS.

Now, to address this specific thread. Since the original inception of Kendo UI (when we had Kendo UI Web, DataViz, and Mobile as separate packages) there has been a ton of evolution in the web world when it comes to writing web applications that can serve mobile. There has been a general shift from mobile-specific websites (think m.website.com or website.com/m/) and in the mobile space we have seen Cordova rise as the best (and at the time almost only) cross-platform solution to the creation and meteoric rise of cross-platform frameworks like React Native, NativeScript, Xamarin, Flutter. Progressive Web Apps (PWAs) have also become a bigger part of our day-to-day, allowing websites to add native functionality in either mobile or desktop scenarios - often eliminating the need for a native mobile app altogether.

On the CSS front Kendo UI moved from LESS over to Sass, allowing for tons of improvements along the way.

With this shift the development efforts within Kendo UI has also shifted to providing web components that can work across all platforms regardless of view port and can allow developers to extend their web apps with native functionality through PWAs to cover much of the same functionality. We've seen this through the extraction of certain Kendo UI Mobile-specific UI components that have since been added into the "rest" of Kendo UI, like the Switch being moved out of the Kendo UI Mobile namespace, as well as additional UI components like the ActionSheet and Popover.

Our ultimate goal here is to provide developers working within the Cordova space the ability to use the same components they would in the web space but also provide them with up-to-date Sass themes for all of these components. With R3 2021 we will have full coverage of all Kendo UI Mobile components and this should allow developers to find instances of the mobile-equivalent and replace them component-by-component e.g. `kendo.ui.mobile.button` can be replaced by the `kendo.ui.button`. The same features (and more) are available, and there's never been anything stopping developers from adding the rest of the jQuery UI components to their hybrid mobile apps, but now it's even more appropriate.

Unfortunately we will not be able to re-write the Kendo UI Mobile themes to Sass, especially considering that these themes are targeting pretty old versions of each of the frameworks we targeted. I believe iOS 6 and Android 4 were the last versions that had the look-and-feel of the Mobile themes, and Windows Phone is no longer a platform.

Does this mean that there will be certain aspects of apps that will need to be updated and re-written? Absolutely, and we understand the frustration that may come from this. However, from our own internal testing we have seen success with targeting specific UI components and placing their instances with the web equivalent without having to to a full re-write. We also understand that this may be something that you need some assistance with and our support team is ready and standing by for any specific issues that you may run into during this migration.

While I understand that all of this may still leave folks with a sense of frustration, especially with the lack of clear communication in this thread, hopefully this background and additional information from our side will give insight into where we are today and our thoughts behind all of this.
