### ISSUE TITLE
NumericTextBox overflows next content in Edge

### ISSUE THREAD

**Issue by vladimirivanoviliev** [telerik/kendo-themes#812]
## I'm submitting a...
* Bug report 

## Current behavior
Adding text after NumericTextBox in Edge browser puts the text below the component as seen in following screencast. Issue is reproducible in both Angular and React version of components:

![image](https://user-images.githubusercontent.com/2195951/60803089-1664c000-a183-11e9-8c21-985425229dc0.png)

## Expected behavior
The text added after the component to be visible (not overflowed by the editor).

## Minimal reproduction of the problem with instructions

* [Demo](https://stackblitz.com/edit/angular-csbskn?file=app/app.component.ts)

## Environment
Product:
* Kendo Ui for Angular
* Kendo Ui for React

Browser:
- **Edge** version: Microsoft Edge 41.16299.1004.0 / Microsoft EdgeHTML 16.16299

**Comment by TeyaVes** [comment]
In fact, the issue is not really the fact that the text added after the input is hidden, but rather that the up and down arrows are outside of the input container in Edge.

This is happening due to a bug in Edge- a _min-width: 0_ needs to be added to the input since its wrapper is flex. 

The suggested style is already added in the Sass themes, but it targets elements which are children of element with class _.k-edge_. In Kendo jQuery, the respective class is added to the body, but in Angular/React, it is not. 

This is why a solution would be to add the respective browser class to the numerictextbox  wrapper:

![edge](https://user-images.githubusercontent.com/45764088/61883616-6f628100-af03-11e9-8fe8-8022f853d350.png)
