### ISSUE TITLE
Invalid CSS output when compiling SCSS stylesheets

### ISSUE THREAD

**Issue by tomvanoost** [telerik/kendo-themes#834]
## I'm submitting a...

* Bug report 

## Current behavior

Some SCSS variables are declared without a unit:
```
$switch-container-padding-x: 0 default!;
$switch-container-border-width: 0 default!;
```

When they are used in CSS calculations this leads to invalid expressions, like:
```
.k-switch-label-off {
    right: calc(8px - 0);
}
```

## Expected behavior

It should compile as follows:
```
.k-switch-label-off {
    right: calc(8px - 0px);
}
```

## Workaround
Override the variables in your own custom SCSS.
```
$switch-container-padding-x: 0px;
$switch-container-border-width: 0px;
```

## Environment
Product:

* Kendo for Angular: kendo-default-theme, version 4.1.0.

Browser:

- Chrome (desktop) version XX

**Comment by joneff** [comment]
just to confirm, this is happening with angular 8 or dart-sass, correct?

**Comment by tomvanoost** [comment]
@joneff Yes, this is correct. It happens with Angular 8 and the dart-sass compiler.

**Comment by joneff** [comment]
Pardon the delay, I needed to confirm. So the issue is related to how `calc` expressions are treated by browsers. Normally, one would suggest that when adding, type coercion would be applied because 0 can be in any unit.

This can be mitigated by using postcss-calc in the build process and we'll add a how-to topic.

Related to #846, #908.

**Comment by joneff** [comment]
We've provided documentation for:

* [Compiling themes](https://github.com/telerik/kendo-themes/wiki/Compiling-themes)
* [Customizing themes](https://github.com/telerik/kendo-themes/wiki/Customizing-themes)
* [Including themes in React projects](https://github.com/telerik/kendo-themes/wiki/Including-themes-in-React-projects)
* [Including themes in Angular projects](https://github.com/telerik/kendo-themes/wiki/Including-themes-in-Angular-projects)

In the compiling themes article, there are instructions for both webpack and gulp builds. The part that fixes calc expressions is the usage of `postcss-calc`

**Comment by JohannesHoppe** [comment]
If you work with Angular, it is absolutely unusal to configure webpack. This is an open bug and should not be considered as fixed!!

**Comment by joneff** [comment]
@JohannesHoppe, we are open to suggestions on what a fix should be. But first, here is a bit of backstory, so we are on the same page.

Prior angular 8, we had math functions for handling common cases, our now deprecated (and removed) `add-two` or `add-three` functions, which also accepted a multiplier.

At some point, when Angular 8 was to be released, the default sass compiler was switched from node-sass to dart-sass, and with that came some issues, two of them major, one minor:

* [major] extending compound selectors is not allowed, sass/dart-sass#286
* [major] dart-sass threats interpolation differently, sass/dart-sass#718
* [minor] unicode characters are displayed differently, sass/dart-sass#719

*"Major issue", in this case meant that the themes were either not compiled at all, or had invalid output.*

For each issue we had to create a different fix. The fix for the compound selectors issue required a major version, because we refactored the themes in a way that was incompatible with previous version.

Unicode characters issues... we kinda ignored that, because it was not essential.

And then came the interpolation -- our approach was not working at all and the only possible solution was to migrate to `calc` right away, something we avoided because we knew some browsers had issues with nested calc expressions and then was the zero value in calc, which surprisingly does not work.

Sure, we could have changed all values to `0px`, but then if anyone had set a variable to be explicitly `0` or some expressions were nested, we arrive at the original problem -- there is invalid output.

Since having zeros in calc expressions or nested calc expressions is not limited to just our packages, nor we are the first to encounter them, we relied on postcss-calc to ensure our dist css was both valid and understandable by browsers. Having tackled the issue, we documentation how to handle the case should it arise when compiling the themes from source.

It's worth noting that about two months after we removed the math functions 604a7309c9b09be4f65ac0914036f6c0409116d0, the bootstrap team probably encountered similar problem and they tackled it differently -- twbs/bootstrap@7bd70e54f2c02e0885b9da5d87a5caac5d963fae -- by creating a generic `add` function that works around the string interpolation limitation in dart sass, but still may end up with nested calc expressions.

Neither solution is ideal, but both fit the cases.

The three issues above (string interpolation differences between, unicode output and extending compound selectors) are is considered **by design** or a **feature** and not bugs by the sass team. True, I may not agree with them, but they have provided guidance how to handle the issue.

You could say that the invalid css output is a feature / by design when compiling the themes from source -- we have deliberately chosen this approach and we provide you, and other developers, with information how to mitigate the issue, should it arise.

And that's the whole backstory.

Like I said in the beginning, we are open to suggestions.

**Comment by JohannesHoppe** [comment]
Wow, thank you very much for the detailed explanation! So I understand your situation much more now! BUT I think for a paid product, the upgrade path must be as simple as possible. As an already too busy developer, I don't want to deal with this kind of problems! Please solve this for me before I have to search on GitHub! 😉

My suggestion is the following. You should investigate even more into Angular Schematics for upgrades! Other solutions like Angular Material are already doing it and all upgrades are completely painless.

So please not only provide this:
```
ng add @progress/kendo-angular-dialog
```

But also this:
```
ng add @progress/kendo-theme-default
ng update @progress/kendo-theme-default
```

In a perfect world, the schematic would analyse my project and do all required fixes automatically. E.g last time Angular Material removed polyfills weren't required anymore. No changelogs, no bug hunting. 

If this is a too big investment for you, I could live with a minimal solution where `kendo-theme-default` just adds some additional lines into my styles.scss:

```
// if you are still using node-sass (default until Angular 7) with Angular 8+, enable-rounded won't work anymore
// see https://github.com/telerik/kendo-themes/issues/1403
// SOLUTION:
// $enable-rounded: false;

// if your are using dart-sass (default since Angular 8), please apply the following lines so the theme compiles
// see https://github.com/telerik/kendo-themes/issues/834
// SOLUTION:
// $switch-container-padding-x: 0px;
// $switch-container-border-width: 0px;

```
No matter which solution you choose: GitHub issues should be really the last resort and should not be required for a normal upgrade!

**Comment by joneff** [comment]
Comparing kendo-themes to other projects, like `@angular/material` or `@material-ui/core` doesn't really add to the discussion -- the former is a complete bundle for both components and themes for angular built on top of material design and the latter is the same, but for react. Kendo themes is different in the regard that we use the same theme code base (mostly, actually due to how host elements work in angular) for jquery, vue, angular, react and blazor.

That being said, angular schematics might help alleviate some of the compilation specifics of the themes, such processing calc expressions, for angular developers that is, so I've logged it #1462.

We can't promise friction less updates, though. For instance when we release v5 of the themes, they will have completely different structure and some manual work will be required.

The same goes for changes in the theme due to changes in either dart-sass or node-sass compilers -- sometimes they are breaking in nature, such were the cases for compound selectors and string interpolation, which lead us to this thread.

But going back to my sentence about using the same themes for multiple frameworks, we can't really neglect one framework users for another. So whatever the solution may be, that will result in the schematics for angular, will have to make sure it's adaptable to other users as well.

As a first step, we can move the compilation documentation from the wiki of this project to the actual themes.
