### ISSUE TITLE
calc() not working properly when there is a 0 value

### ISSUE THREAD

**Issue by elena-gancheva** [telerik/kendo-themes#846]
In an Angular 8 project with kendo-theme-material loaded, the grid pager item size is not calculated properly, because there is a `button-border-width` value set to `0` and not to `0px`.

The workaround is to override the `button-border-width` to `0px`: 
$button-border-width: 0px;
@import '~@progress/kendo-theme-material/scss/all';

see the image attached:
![image](https://user-images.githubusercontent.com/8842674/62698771-a26a4180-b9e6-11e9-8498-5384a9bc9044.png)

**Comment by billypopper7** [comment]
I am seeing the same issue with the Switch control. It causes the labels to be out of place. 
![image](https://user-images.githubusercontent.com/11202164/62795058-6ba23300-ba9b-11e9-9827-04011ea5da6f.png)
I am using Angular 8 and the default styles

The workaround is the same but override `switch-container-border-width` to `0px`:
$switch-container-border-width: 0px;
@import "~@progress/kendo-theme-default/scss/all";

**Comment by joneff** [comment]
Prior support for dart-sass (41d3f2be4a056b066e14d9769be99b0d3039c4dc), the issue was not present. What changed?

Dart-sass works differently with strings. Previously, we compiled the strings trough utility functions, which unfortunately do not work in dart sass. The strings were usually the smallest possible form, say if you have `calc(8px + 1px)` it would yield `9px` or in the case of the problematic expression it would simply strip the 0.

To tackle this, we plugged postcss-calc and works on much more complicated examples, which understandably not everyone is fine using.

What @elena-gancheva  suggests will fix the issue, but now, in the output all borders will be `0px` instead of `0` and linting tools will complain.

In addition, the way the variables work and cascade, there is no guarantee that somewhere else the variable will not be overridden to `0` and break again. We respect all previous values of variables and if the previous value is `0` things will break again.

**Comment by DaleyKD** [comment]
I have the same problem.

However, using SASS in Visual Studio 2019, and Mads Kristensen's Web Essentials 2019, the workaround doesn't work. However, 

`$button-border-width: 0.1px;`

At least gives the output of:
`calc(1*(.2px + 16px + 1.42857em))`

Notice the 2x multiplier on the first px.

For today, this will suffice.  Though, I am concerned about other controls that will have issues somewhere.

**Comment by joneff** [comment]
We've provided documentation for:

* [Compiling themes](https://github.com/telerik/kendo-themes/wiki/Compiling-themes)
* [Customizing themes](https://github.com/telerik/kendo-themes/wiki/Customizing-themes)
* [Including themes in React projects](https://github.com/telerik/kendo-themes/wiki/Including-themes-in-React-projects)
* [Including themes in Angular projects](https://github.com/telerik/kendo-themes/wiki/Including-themes-in-Angular-projects)
