### ISSUE TITLE
The Switch, the DropDownList and the DatePicker components look different when placed inside a Toolbar.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-themes#850]
The Switch, the DropDownList, and the DatePicker components look different when placed inside a Toolbar.

This is observed only in the Material theme.

This is an example using the KendoReact components:

https://stackblitz.com/edit/react-pns7jw?file=index.html

**Comment by Juveniel** [comment]
Here is additional information regarding the issues:

* Switch looks bigger than expected inside the Toolbar - caused by the Switch explicit font-size.

* DropDownList DatePickers missing bottom border - actually [according to the design ](https://github.com/telerik/kendo-ux/blob/master/themes/material/PNG/toolbar.png)the normal state of the widgets should not include a bottom border.

Taking the above into consideration, the suggested fix targets only the Switch.
