### ISSUE TITLE
Grid with paging - adjust container height instead of showing scroll by default

### ISSUE THREAD

**Issue by sdurnov** [telerik/kendo-themes#90]
There's not much sense in showing vertical scroll bar in paged grid (especially, when there's nothing to scroll). It just eats space and adds visual clutter. Adjusting container's height automatically is just much more convenient default.
Example:
https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/#

**Comment by joneff** [comment]
I know this issue is long overdue for an answer and the more time passes, the more irrelevant the answer is. As of today, on the demo page you referenced, the grid height is adjusted.

On a side note: the fix was not provided by the themes, but rather the angular components. We try not to set the height from the css, even though we do so in certain cases.
