### ISSUE TITLE
Grid - disable row alternation by default

### ISSUE THREAD

**Issue by sdurnov** [telerik/kendo-themes#91]
Row alternation as a default isn't really much helping. Providing default without alternation is just visually lighter and cleaner solution IMO. Turning it off by specifically setting class binding - really much more, than you'd like to do to get it working.

**Comment by gyoshev** [comment]
Arguably, alternating rows guide the user's eye across the row data, and are in fact helpful. You can remove the alternating effect by setting the [`$grid-alt-bg` variable](https://github.com/telerik/kendo-themes/blob/develop/packages/default/scss/grid/_theme.scss#L5). I'll document it shortly, so that it is persisted between official versions.
