### ISSUE TITLE
Get rid of magic numbers and weird expressions

### ISSUE THREAD

**Issue by sdurnov** [telerik/kendo-themes#92]
Right now, while trying to customize Default theme, I'm seeing various lines of code, which makes customizing theme complicated for me. (I'm using Kendo for Angular together with Bootstrap 4)

Here are the examples:

**from _variables.scss**

`$font-size: 14px !default;`

Why not to just set it to 1rem by default?

```
$padding-x: 8px !default;
$padding-y: 4px !default;
```

Why hardcoding it in px? Why not to bound it to $spacer variable with multiplier so it will scale proportionally through media breakpoints?

`$border-color: rgba( black, .08 ) !default; `

Usage of rgba function produces values, that are hard to trace/search

**from combobox/_layout.scss**

```
.k-dropdown-wrap {
            > .k-i-close {
                right: calc(#{$icon-size} + #{$padding-y-lg * 3});
            }
        }
```

Why are you using $padding-y-lg * 3 ?
Weird formula. If you make padding bigger, then clear icon goes way too much to the left.

**Comment by gyoshev** [comment]
@sdurnov you are correct about some undocumented weirdness in the themes, and we are constantly trying to eliminate these. That said, I am afraid that the scope of this issue is too vague to be fixable, and this is why I'm closing it. An effective approach on getting these addressed would be to open issues for specific cases that block your development cycle, and address them case by case.

To answer your question more generally, some of the values are directly ported from legacy themes and are not yet refactored and haven't undergone sufficient peer review.
